Name: product.rpc
ListenOn: 0.0.0.0:9001
Etcd:
  Hosts:
  - etcd:2379
  Key: product.rpc

Mysql:
  DataSource: root:123456@tcp(mysql:3306)/gomall?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai

RedisCache:
  - Host: redis:6379
    Type: node
    Pass:

RedisConf:
  Addr: redis:6379


Prometheus:
  Host: 0.0.0.0
  Port: 9091
  Path: /metrics

Telemetry:
  Name: product.rpc
  Endpoint: http://jaeger:14268/api/traces
  Sampler: 1.0
  Batcher: jaeger
