Name: Product
Host: 0.0.0.0
Port: 8001

Auth:
  AccessSecret: uOvKLmVfztaXGpNYd4Z0I1SiT7MweJhl
  AccessExpire: 86400

ProductRpc:
  Etcd:
    Hosts:
      - etcd:2379
    Key: product.rpc

Prometheus:
  Host: 0.0.0.0
  Port: 9081
  Path: /metrics


Telemetry:
  Name: product.api
  Endpoint: http://jaeger:14268/api/traces
  Sampler: 1.0
  Batcher: jaeger
